--liquibase formatted sql
--changeset yulia:1
CREATE SCHEMA IF NOT EXISTS MY_NEW_APP;

--changeset yulia:2
CREATE TABLE IF NOT EXISTS MY_NEW_APP.CUSTOMERS
(
    ID           BIGSERIAL PRIMARY KEY,
    NAME         VARCHAR(100),
    SURNAME      VARCHAR(100),
    AGE          INTEGER,
    PHONE_NUMBER VARCHAR(50)
);

--changeset yulia:3
CREATE TABLE IF NOT EXISTS MY_NEW_APP.ORDERS
(
    ID           BIGSERIAL PRIMARY KEY,
    DATE         DATE,
    CUSTOMER_ID  BIGINT,
    PRODUCT_NAME VARCHAR(200),
    AMOUNT       INTEGER,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES MY_NEW_APP.CUSTOMERS (ID)
);
